docker-monitor-influxsrv:
  image: docker-registry:443/emergya/influxdb:0.8.8
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=cadvisor
docker-monitor-cadvisor:
  image: docker-registry:443/emergya/cadvisor:v0.20.1
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
  ports:
    - "9090:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - docker-monitor-influxsrv:influxsrv
docker-monitor-grafana:
  image: docker-registry:443/emergya/grafana:2.0.2
  ports:
    - "3000:3000"
  links:
    - docker-monitor-influxsrv:influxsrv
  environment:
    - INFLUXDB_HOST=localhost
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=cadvisor
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root

